[build-system]
requires = ["setuptools >= 61.0", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "boom"
version = "0.0.0"

dependencies =[
    "numpy",
    "scikit-learn",
    "matplotlib",
    "seaborn",
    "rdkit",
    "tqdm",
    "requests",
    "chemprop>=2.2.0",
    "lightning>=2.0",
    "umap-learn>=0.5",
    "xgboost>=2.0",
]
readme = "README.md"
requires-python = ">=3.11"

[project.optional-dependencies]
viz = ["matplotlib", "seaborn"]

[tool.setuptools]
include-package-data = true
zip-safe = false
packages = ["boom"]

[tool.ruff]
line-length = 120

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
]
